/**
 * Which user-role turns are the harness talking to itself.
 *
 * **An allowlist of tags observed in Claude transcripts, never a shape.** The
 * filter this replaces stripped every paired tag and dropped the turn if nothing
 * survived, which deletes a person's paste. Measured against it:
 * `<code>port: 8080</code>`, `<p>hello</p>`, `<td>1</td><td>2</td>` and
 * `<name>svc</name>` were all deleted from the index; a *nested* snippet
 * survived only by leaving one unmatched closing tag behind. The accident, not
 * the intent, was doing the work.
 *
 * Those tags are not rare. Across 720 local session files: `<code>` 3742,
 * `<p>` 3313, `<td>` 3213, `<summary>` 1668, `<details>` 433.
 */

/**
 * The eleven attested in this corpus, with their occurrence counts.
 *
 * Counts are here because they are the evidence for membership: a tag nobody has
 * seen does not belong in an allowlist, however plausible it sounds.
 */
export const HARNESS_TAGS: ReadonlySet<string> = new Set([
  'task-notification', // 1343
  'command-name', //      148
  'command-message', //   122
  'command-args', //      121
  'local-command-stdout', // 98
  'system-reminder', //    75
  'local-command-caveat', // 63
  'bash-input', //         21
  'bash-stderr', //        21
  'bash-stdout', //        21
  'user-prompt-submit-hook', // 1
]);

/**
 * In orca's list, absent from this corpus.
 *
 * Not enabled, and the reason is orca's own: only observed tags count. Its list
 * is shared across seven agent vendors, so an entry may be another harness's
 * vocabulary rather than Claude's. Each of these is a plausible Claude Code
 * feature simply unexercised here — cross-session messaging, MCP resources,
 * memory input, forking.
 *
 * Promote one by moving it up, once a transcript shows it. That is a one-line
 * change backed by evidence rather than a guess copied from another project.
 */
export const CANDIDATE_TAGS: ReadonlySet<string> = new Set([
  'agent-message',
  'cross-session-message',
  'fork-boilerplate',
  'local-command-stderr',
  'mcp-polling-update',
  'mcp-resource-update',
  'teammate-message',
  'user-memory-input',
]);

/**
 * Injected turns known by a leading string rather than a tag name.
 *
 * `<channel source=` is the attributed form and is deliberately not a bare
 * `<channel>`: that one is an ordinary RSS paste.
 */
const PREFIXES: readonly string[] = [
  '[request interrupted',
  'caveat: the messages below were generated by the user while running local commands',
  'this session is being continued from a previous conversation',
  '<channel source=',
];

/**
 * Only the head is inspected, so classification costs a fixed slice rather than
 * a lowercase copy of a multi-megabyte paste.
 */
const HEAD = 256;

/** A leading tag, and only a leading one — a mention mid-sentence is prose. */
const LEADING_TAG = /^<([a-z][a-z0-9-]*)[\s>]/;

export function isHarnessInjectedText(text: string): boolean {
  const head = text.slice(0, HEAD).trimStart().toLowerCase();
  if (head === '') return false;

  const tag = LEADING_TAG.exec(head);
  if (tag !== null && HARNESS_TAGS.has(tag[1])) return true;

  return PREFIXES.some((prefix) => head.startsWith(prefix));
}
