package com.eshaan.shepherd.v2

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The net's trust core on the phone, held to bytes the MAC actually produced.
 *
 * Every fixture below was generated by `packages/remote` and pasted here
 * verbatim: the canonical strings a signature covers, a real credential, and the
 * Ed25519 signature the Mac put on it. That is the only honest way to test an
 * interop layer without running both sides — a Kotlin test that signs and then
 * verifies with its own code proves the two halves of THIS file agree and
 * nothing about the Mac.
 *
 * If a change here makes these fail, the phone has stopped speaking the host's
 * protocol, whatever else still passes.
 */
class NetTest {
    private val netId = "f186e88c7ed87c2c9913d490796e285d5f70f58931d490bf7376e8fc5efab54f"
    private val rootPublicKey =
        "302a300506032b65700321002e2b6d5afe0988e03abae777aadaac67640f966d0652be9bc71e076cc212c991"

    /** A founder's credential, signed by the net's root key on the Mac. */
    private val founder = Credential(
        netId = netId,
        epoch = 1,
        memberId = "mac-mini",
        // Deliberately awkward: a quote and a newline, because the canonical
        // form is JSON and escaping is exactly where two languages disagree.
        name = "Mac \"mini\" \n2",
        publicKey = "aa".repeat(44),
        certPin = "bb".repeat(32),
        issuedAt = 1786432699202L,
        issuer = Net.ROOT,
        signature =
            "4eb6f24dbd619c4a6b9135d2a9f3d36c648c77817fef086a71a483a2e1d2757278288ee93ead4c9d24bc99c28e0b11f6" +
                "fe96912e3cc5fb9e5e453b82e0d19e0f",
    )

    @Test
    fun `canonical credential bytes match the host's`() {
        val expected =
            """["shepherd-net-credential-v1","$netId",1,"mac-mini","Mac \"mini\" \n2","${"aa".repeat(44)}",""" +
                """"${"bb".repeat(32)}",1786432699202,"root"]"""
        assertEquals(expected, String(Net.credentialBytes(founder), Charsets.UTF_8))
    }

    @Test
    fun `canonical proof bytes match the host's`() {
        assertEquals(
            """["shepherd-net-proof-v1","$netId","${"cc".repeat(32)}",1786432699202]""",
            String(Net.proofBytes(netId, "cc".repeat(32), 1786432699202L), Charsets.UTF_8),
        )
        assertEquals(
            """["shepherd-net-host-proof-v1","$netId","a-nonce"]""",
            String(Net.hostProofBytes(netId, "a-nonce"), Charsets.UTF_8),
        )
    }

    /** The interop assertion: a signature the MAC made, checked here. */
    @Test
    fun `a signature made on the Mac verifies on the phone`() {
        assertTrue(NetCrypto.verify(rootPublicKey, Net.credentialBytes(founder), founder.signature))
    }

    @Test
    fun `the net id is the hash of the root key, as the Mac derives it`() {
        assertEquals(netId, NetCrypto.netIdOf(rootPublicKey))
    }

    @Test
    fun `a signature over edited bytes does not verify`() {
        val renamed = founder.copy(name = "Not the Mac mini")
        assertFalse(NetCrypto.verify(rootPublicKey, Net.credentialBytes(renamed), founder.signature))
    }

    @Test
    fun `a malformed key or signature is refused rather than thrown`() {
        // Fed whatever a peer sent, so this is reachable rather than theoretical.
        assertFalse(NetCrypto.verify("not-a-key", byteArrayOf(1), "zz"))
        assertFalse(NetCrypto.verify(rootPublicKey, byteArrayOf(1), "not-hex"))
    }

    @Test
    fun `a minted key signs what it can verify, and nothing else can`() {
        val mine = NetCrypto.generateMemberKey()
        val theirs = NetCrypto.generateMemberKey()
        val message = "hello".toByteArray()
        assertTrue(NetCrypto.verify(mine.publicKey, message, NetCrypto.sign(mine.privateKey, message)))
        assertFalse(NetCrypto.verify(mine.publicKey, message, NetCrypto.sign(theirs.privateKey, message)))
        assertNotEquals(mine.publicKey, theirs.publicKey)
    }

    @Test
    fun `a key round-trips through the hex DER the wire carries`() {
        val key = NetCrypto.generateMemberKey()
        // 44-byte SPKI and 48-byte PKCS8 — the encodings the Mac reads back.
        assertEquals(88, key.publicKey.length)
        assertTrue(NetCrypto.verify(key.publicKey, byteArrayOf(7), NetCrypto.sign(key.privateKey, byteArrayOf(7))))
    }

    // ------------------------------------------------------------------ chains

    private fun chainOf(vararg links: Credential) = links.toList()

    @Test
    fun `a chain to the root is accepted`() {
        assertNull(Net.verifyChain(chainOf(founder), netId, rootPublicKey, emptySet()))
    }

    @Test
    fun `a chain for another net is refused`() {
        val why = Net.verifyChain(chainOf(founder), "00".repeat(32), rootPublicKey, emptySet())
        assertTrue(why!!.contains("different net"))
    }

    @Test
    fun `a chain signed by another root is refused`() {
        val other = NetCrypto.generateMemberKey().publicKey
        assertNotNull(Net.verifyChain(chainOf(founder), netId, other, emptySet()))
    }

    @Test
    fun `a revoked member is refused, and so is anyone it admitted`() {
        assertNotNull(Net.verifyChain(chainOf(founder), netId, rootPublicKey, setOf("mac-mini")))

        val key = NetCrypto.generateMemberKey()
        val issued = Net.issue(
            netId = netId,
            epoch = 1,
            memberId = "phone",
            name = "Phone",
            publicKey = key.publicKey,
            certPin = "",
            issuedAt = 1,
            issuer = "mac-mini",
            privateKey = key.privateKey, // wrong signer on purpose — see below
        )
        // Signed by the phone rather than by its issuer, so it must not verify:
        // this is the "a chain is public, anyone can claim to have been admitted"
        // case, and the signature is the only thing that answers it.
        assertNotNull(Net.verifyChain(chainOf(issued, founder), netId, rootPublicKey, emptySet()))
    }

    @Test
    fun `an empty chain is refused`() {
        assertNotNull(Net.verifyChain(emptyList(), netId, rootPublicKey, emptySet()))
    }

    private fun assertNotNull(value: String?) = assertTrue("expected a refusal", value != null)
}
